apiVersion: apps/v1
kind: Deployment
metadata:
  name: haidy-deployment
  labels:
    app: haidy
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haidy
  template:
    metadata:
      labels:
        app: haidy
    spec:
      containers:
      - name: haidy
        image: haidyh/haidy-web-app-v1:latest
        ports:
        - containerPort: 80
